### ISSUE TITLE
Icon request: us-flag-straight

### ISSUE THREAD

**Issue by patricknowlan** [540co/govicons#1]
I am thinking it would be useful to have two versions of the usa flag. One where it is curvy and another where it is just straight. I am using the [18F Web Design Standards](https://github.com/18F/web-design-standards) and they use a straight flag for the usa-disclaimer and in the usa-banner... view source on [their website](https://playbook.cio.gov/designstandards/) to see what I am talking about.

I would also like to have a straight flag for general use in all of my applications. :us: !!!

**Comment by patricknowlan** [comment]
Something like this but without the colors of course:

![image](https://cloud.githubusercontent.com/assets/6303436/11480739/2e725a10-9767-11e5-9697-c36f5a02ed7c.png)

**Comment by ostranme** [comment]
added to 1.1.0
