### ISSUE TITLE
Icon request: justification book

### ISSUE THREAD

**Issue by jobrieniii** [540co/govicons#23]
it was also be nice to possible have a way to differentiate procurement vs. rdte

http://acqnotes.com/acqnote/acquisitions/budget-exhibits

**Comment by mandy6720** [comment]
Maybe the book icon with the letter J in it?

**Comment by ostranme** [comment]
Not sure we really need a icon for a justification book. I would just use the book icon thats available already. Would rather have the text differentiate the two different kinds rather then possibly confuse the user with icons. We can keep this open and if there is a need for it we can track it here.

**Comment by jobrieniii** [comment]
maybe some type of overlay of two icons (book with dollar sign, etc)

**Comment by ostranme** [comment]
Agree @jobrieniii. You can achieve using css. Closing for now.

Example here:
https://plnkr.co/edit/4opMe7wUBJdOHYr5JU8k?p=preview
