### ISSUE TITLE
Icon Requests: gi-construction, gi-barricade, gi-road (Construction and Road Projects)

### ISSUE THREAD

**Issue by made4gov** [540co/govicons#30]
Can you please create construction, barricade, and road icons?

Many local and state governments do a number of construction projects and currently the major icon offerings do not include anything very good for these items. 

Construction and barricade icons could be used to signify a page/section that is under construction, construction taking place, or to signify a government project. 

Road icons could be used to signify the DOT, road projects, etc.

Here are a couple examples:
Construction: https://d30y9cdsu7xlg0.cloudfront.net/png/2029-200.png
Construction Tools: http://content.presentermedia.com/files/clipart/00015000/15780/construction_tools_cross_icon_md_wm.jpg 
Barricade: http://icons.iconarchive.com/icons/iconsmind/outline/512/Barricade-icon.png 
Road: http://image.flaticon.com/icons/svg/55/55166.svg 

Thank you!

**Comment by ostranme** [comment]
@made4gov Thanks for submitting a request. I'll take a look into adding a couple of these for the next release. I can add icon-construction, icon-road, and icon-barricade.

Right now we currently have gi-tools. Is this icon sufficient enough for your needs of construction tools?

**Comment by made4gov** [comment]
Awesome! Thanks! I appreciate the set you guys have created.

Yes, tools is good. Missed that one.

**Comment by ostranme** [comment]
Good to hear. Will update you once we start adding them so you can test out.

**Comment by ostranme** [comment]
@made4gov Added gi-construction, gi-road, and gi-road-barricade

Completed in v1.3.0
