### ISSUE TITLE
Icon request: gi gi-trump-hair

### ISSUE THREAD

**Issue by piq9117** [540co/govicons#46]

**Comment by ostranme** [comment]
@piq9117 Thanks for the suggestion! Could you please add a description of how you might use this potential icon. Would like to know if it's of any need soon or just an issue to considered.

**Comment by piq9117** [comment]
No urgency. Just a request to be considered. Btw, thank you for this great project!

**Comment by piq9117** [comment]
No urgency. Just a request to be hopefully considered. Btw, thanks for this great project!

**Comment by ostranme** [comment]
No problem, thanks for the feedback! We love seeing this library grow so please feel free to open additional issues or requests. I think for now the icon could be seen as a negative OR positive connotation (depending how you look at it). I don't want to raise a political fire regardless of how you see it, so we might leave out for now and consider it for the future. I'm happy to work outside of the project if you want an alternative for the icon. Just let me know.
