### ISSUE TITLE
Icon request: gi-poison

### ISSUE THREAD

**Issue by mika76** [540co/govicons#47]
You have a radioactive and bio-hazard icon but not a poison one which kinda fits into the list... (scull or scull with crossbones)

**Comment by ostranme** [comment]
Thank you for the suggestion! Will start planning some concepts and loop you in on initial design/thoughts

**Comment by ostranme** [comment]
@mika76 You can pull down 1.4.0-wip branch and test out the new icons. I've added two poison icons (gi-poison and gi-poison-bottle). Once I finishing testing and updating the docs, I'll tag a new version and push to bower/npm.

**Comment by mika76** [comment]
That's brilliant @ostranme thanks for all the hard work

**Comment by ostranme** [comment]
Added in v1.4.0
