### ISSUE TITLE
github user page govicons.io not working 

### ISSUE THREAD

**Issue by risacher** [540co/govicons#62]
the webfont links are returning 403. 

Specifically: 
http://govicons.io/fonts/govicons-webfont.ttf
http://govicons.io/fonts/fontawesome-webfont.woff2?v=4.5.0
http://govicons.io/fonts/govicons-webfont.woff
http://govicons.io/fonts/govicons-webfont.woff2

**Comment by ostranme** [comment]
Hey @risacher - is there a reason why you are trying to access the served fonts from the github pages site?  I was able to download the 4 links above using Chrome, FireFox, and Safari.

Let me know if you continue to have issues but as of right now I would suggest downloading the fonts using npm, bower, or downloading/cloaning the repo vs accessing the served font files of the github pages website. By default github pages uses HTTP and not HTTPS which might be your issue?

**Comment by risacher** [comment]
The font files weren’t loading, so govicons.io didn’t render any of the icons and the page just showed blank rectangles.  But it works okay today on my phone, so it might just be a firewall blocking the http fonts?  I was accessing from the office

**Comment by ostranme** [comment]
Yep looks like if you are on a secured network it blocks web fonts. I've encounter similar issues before with Font Awesome and have had to have the fonts trusted or accepted. I'm not sure we can do anything if the webfont files are being blocked.

**Comment by ostranme** [comment]
Closing for now since this isn't an issue with font.
