### ISSUE TITLE
Any chance of hosting this on a public CDN?

### ISSUE THREAD

**Issue by ghartsho** [540co/govicons#63]
Is there any interest in hosting this on a public CDN?

**Comment by ostranme** [comment]
Yea that's something we have considered in the past. Let me look back into that and get back to you. I don't see why we couldn't try to support that. 

Could you describe your use-case if we go down the path of hosting on a public CDN? More for prototyping and quickly using the icons from a CDN link?

**Comment by ostranme** [comment]
@ghartsho You can use Unpkg for now: https://unpkg.com/govicons@1.4.1/css/govicons.min.css

We are look into providing our own CDN for Govicons.

**Comment by ostranme** [comment]
@ghartsho Does the above link work for you? If so, can I consider this issue closed?

**Comment by ghartsho** [comment]
Yes, thank you
