### ISSUE TITLE
Relative fonts path missing from govicons.min.css?

### ISSUE THREAD

**Issue by ctr1key** [540co/govicons#74]
The web font src URL in css/govicon.min.css seems to have lost the relative '../fonts/' path in the recent commit. 
The relative path still exists in css/govicon.css so I wasn't sure if this an intentional change.
For the time being, I've just switched to using govicon.css since my build wasn't able to resolve the src URL using govicon.min.css.

**Comment by ostranme** [comment]
Will check it out and try to provide a patch soon.

**Comment by ostranme** [comment]
@ctr1key - Relative font paths have been fixed in **1.5.1**. Feel free to update from 1.5.0 and test. I'll close the ticket once we validate from your end.

**Release:** https://github.com/540co/govicons/releases/tag/1.5.1

**Comment by ctr1key** [comment]
@ostranme - The issue is resolved with 1.5.1. Thanks!
