### ISSUE TITLE
Icon not displaying when specifying size

### ISSUE THREAD

**Issue by cmwilliams** [540co/govicons#77]
I'm using the latest version of Angular and the CLI and have installed the icon pack via NPM. I followed the instructions in the Wiki for SCSS/Angular and when adding ` <i class="gi gi-tank"></i>` I see the icon but when I specify ` <i class="gi-2x gi-tank"></i>` I see a blank bordered box. Am I missing anything?

**Comment by ostranme** [comment]
Are you getting console errors? The blank bordered box typically means fonts are loading or the path to the font file is incorrect. 

Let me know and I'll try to test it out myself to see if anything is different.

**Comment by ostranme** [comment]
I didn't read fully...

@cmwilliams looks like there were a few types in the wiki and the `.gi` class is missing from that example

Could you try the following: `<i class="gi gi-2x gi-tank"></i>`?

**Comment by cmwilliams** [comment]
@ostranme  - That was it! Thank you for the quick response and thank you for the awesome icons!

**Comment by ostranme** [comment]
Happy to help, thanks for the support!
