### ISSUE TITLE
Icon request: gi-bald-eagle

### ISSUE THREAD

**Issue by fixedd** [540co/govicons#78]
## What can it be used for?

It's one of our national symbols... can be used as a, um, symbol :P

## Example image (optional)

I don't have much of an opinion here... perhaps something like https://svgsilh.com/image/46432.html

## Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: hipster-coder`)
- [x] I have [searched for existing issues](https://github.com/540co/govicons/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)

**Comment by ostranme** [comment]
@fixedd Request received. Will start looking into concepts and get back to you before adding to the library. Thank you for your suggestion. Will look to add something here soon.

**Comment by ostranme** [comment]
@fixedd You should now have `gi-bald-eagle` available in `govicons@1.6.0` release. Thanks for the suggestion!
